### ISSUE TITLE
snowpack installing... TypeError: Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by adrianhunter** [jakedeichert/svelvet#33] opened 2020-02-03 18:22 UTC
I get this Error when adding a new dependency that is not an ES module by default or other svelte libs that are just pure svelte files. I think I'm missing something about snowpack. It happens when executing the snowpack cli command. Any Ideas?

**Comment by MarcCoet** [comment] 2020-02-03 19:54
I have been seeing this too with an untouched basic example of this repo with the `build` command. It seems to work fine with the `dev` command though. I haven't investigated.

**Comment by jakedeichert** [comment] 2020-02-04 01:17
I haven't seen this yet, and I just ran the basic example from master with the latest version of svelvet.


>  It happens when executing the snowpack cli command

@adrianhunter Do you mean you're running snowpack manually? Because svelvet runs snowpack during builds so the user doesn't have to.

**Comment by jakedeichert** [comment] 2020-02-04 01:20
@MarcCoet if you could provide your node, npm and svelvet versions, that would help 👍

**Comment by FredKSchott** [comment] 2020-02-04 03:50
Sorry about this one everyone, this was caused by an unexpected breakage in our Rollup dependency that didn't follow semver. It's been fixed in the latest version of Snowpack, released today. 

More info here: https://www.pika.dev/npm/snowpack/discuss/64

**Comment by jakedeichert** [comment] 2020-02-04 03:53
@FredKSchott thanks for noticing this issue and replying, very much appreciated!

If anyone runs into this after updating to the latest snowpack, feel free to reopen 👍

**Closed by jakedeichert** 2020-02-04 03:53 UTC
Labels: needs more details
